### PR TITLE
In ``workflow_logger`` display full path of object instead just object id

### PR DESCRIPTION
**Pull request by gbastien**
This is related to #102 

Please review and merge ;-)

Gauthier

### CODE REVIEW

**Comment by gbastien** [comment]
@jensens @hvelarde 
when you have time, could you please review this?
Thank you very much!
Gauthier

**Comment by fredvd** [comment]
LGTM 2. Simple one line change to improve the representation for only logging. 

Why is merging limited to a subset of authorized users on this package in the collective?

**Comment by jensens** [comment]
> Why is merging limited to a subset of authorized users on this package in the collective?

I can not see any restrictions in the settings - nor know I where to restrict this.

**Comment by jensens** [comment]
Found: it was a misconfigured branch protection. I lowered the barrier: merge needs review, needs travis passing but no longer restricted to admins an owners.

**Comment by hvelarde** [comment]
FYI: the Collective is now owner of this package on PyPI.

**Pull request merged**
