### PR TITLE
Fixed `UnicodeEncodeError`.

### PR DESCRIPTION
**Pull request by jianaijun**

### CODE REVIEW

**Comment by frisi** [comment]
thanks @jianaijun 

are you sure we won't get a UnicodeDecodeError if we pass a utf-8 string containing non-ascii characters (don't know if that can possibly be the case - ie. userids or  actions containing umlauts, dunno what event.record.value can contain)?

**Comment by frisi** [comment]
could you add a test for the case this solves and explain (in the changelog) when/why this can possibly happen?

**Comment by jianaijun** [comment]
Registry events, such as modify the recorded value is UTF-8.
Example in Plone 5:  Plone.site_title .

2016-06-13 17:05 GMT+08:00 Harald Friessnegger <notifications@github.com>:

**Comment by hvelarde** [comment]
do you mind adding a test for that?

**Comment by hvelarde** [comment]
superseded by #44

**Comment by rodfersou** [comment]
@jianaijun thank you for the contribuition, I review other places that might get errors and added a test in this PR https://github.com/collective/collective.fingerpointing/pull/44

**Pull request closed without merging**
