### PR TITLE
Avoid ComponentLookupError when plonectl adduser

### PR DESCRIPTION
**Pull request by jianaijun**
Traceback (most recent call last):
  File "/home/free/Plone/zinstance/parts/instance/bin/interpreter", line 355, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/home/free/Plone/buildout-cache/eggs/Products.PlonePAS-5.0.11-py2.7.egg/Products/PlonePAS/pas.py", line 99, in _doAddUser
    retval = _old_doAddUser(login, password, roles, domains)
  File "/home/free/Plone/buildout-cache/eggs/Products.PluggableAuthService-1.11.0-py2.7.egg/Products/PluggableAuthService/PluggableAuthService.py", line 1025, in _doAddUser
    notify(PrincipalCreated(user))
  File "/home/free/Plone/buildout-cache/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/home/free/Plone/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/home/free/Plone/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/free/Plone/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/free/Plone/buildout-cache/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(_objects)
  File "/home/free/Plone/buildout-cache/eggs/collective.fingerpointing-1.1b1-py2.7.egg/collective/fingerpointing/subscribers/pas_logger.py", line 21, in pas_logger
    audit_pas = api.portal.get_registry_record(record)
  File "<string>", line 2, in get_registry_record
  File "/home/free/Plone/buildout-cache/eggs/plone.api-1.5-py2.7.egg/plone/api/validation.py", line 70, in wrapped
    return f(_args, **kwargs)
  File "/home/free/Plone/buildout-cache/eggs/plone.api-1.5-py2.7.egg/plone/api/portal.py", line 275, in get_registry_record
    registry = getUtility(IRegistry)
  File "/home/free/Plone/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 169, in getUtility
    raise ComponentLookupError(interface, name)

### CODE REVIEW

**Comment by hvelarde** [comment]
@jianaijun I can't help you if you don't use a branch instead of a fork.

**Comment by jianaijun** [comment]
@hvelarde I have created a branch: 
https://github.com/collective/collective.fingerpointing/tree/fix-lookup-error 
Thank you for your help。

**Comment by hvelarde** [comment]
I think you didn't update the branch, could you please double check and create a new PR?

**Comment by jianaijun** [comment]
Sorry, I forgot to commit.
https://github.com/collective/collective.fingerpointing/commit/791e0ea3cc24088cb79b2678b577f9c2c4d20a57

2017-01-23 20:17 GMT+08:00 Héctor Velarde <notifications@github.com>:

**Pull request closed without merging**
