### PR TITLE
Add i18n structure for French translations

### LINKED ISSUE #60: French translations
Hi,

I would like to add french translations, I see there is no "fr" folder in locales, we used to run i18ndude to manage translations and add a synch_locales.sh file in locales to ease updates of various translations, could you please tell me how you proceed?  Can I add this helper .sh in locales?

Thank you,

Gauthier

### PR DESCRIPTION
**Pull request by hvelarde**
closes #60

### CODE REVIEW

**Comment by gbastien** [comment]
Hi @hvelarde 

thank you!

Gauthier

**Comment by hvelarde** [comment]
do you need a release?

**Comment by gbastien** [comment]
Hi @hvelarde, that would be nice ;-)

**Comment by hvelarde** [comment]
done! https://pypi.python.org/pypi/collective.fingerpointing/1.4b2

**Pull request merged**
