### PR TITLE
Add translated languages & fix typo

### PR DESCRIPTION
**Pull request by laulaz**

### CODE REVIEW

**Comment by gbastien** [comment]
:+1:

**Comment by gbastien** [comment]
Hi,

that would be great to merge this and to have a new release if nothing is on the way...

Thank you!

Gauthier

**Comment by gbastien** [comment]
> Hi,
> 
> that would be great to merge this and to have a new release if nothing is on the way...
> 
> Thank you!
> 
> Gauthier

@jensens if you prefer, you can give me pypi rights and I'll do the release ;-)

**Comment by jensens** [comment]
@gbastien I do not have permissions here. @hvelarde the Plone release team (@mauritsvanrees @esteele via collective account)

**Comment by mauritsvanrees** [comment]
I tried, but the `collective` account only has the Maintainer role, so I cannot grant someone else a role. So this is up to @hvelarde.

**Comment by mauritsvanrees** [comment]
Well, I can do a release of course... Done:
https://pypi.org/project/collective.fingerpointing/1.8.2/

**Pull request merged**
