### PR TITLE
Fixed issue that lead to error when logging is run by anonymous user

### LINKED ISSUE #57: AttributeError on PAS logger
The following error is happening in one customer site:

```python
2017-06-08T06:19:47 ERROR Zope.SiteErrorLog 1496913587.920.428048948111 https://www.example.org/foo
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module example.org.browser.notification, line 75, in __call__
  Module example.org.browser.notification, line 111, in create_subscriber
  Module plone.api.user, line 89, in create
  Module <string>, line 10, in addMember
  Module plone.protect.utils, line 56, in _curried
  Module <string>, line 10, in addMember
  Module AccessControl.requestmethod, line 70, in _curried
  Module Products.CMFCore.RegistrationTool, line 160, in addMember
  Module Products.PlonePAS.tools.membership, line 163, in addMember
  Module Products.PlonePAS.pas, line 99, in _doAddUser
  Module Products.PluggableAuthService.PluggableAuthService, line 1025, in _doAddUser
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module collective.fingerpointing.subscribers.pas_logger, line 27, in pas_logger
  Module collective.fingerpointing.utils, line 9, in get_request_information
AttributeError: getMemberId
```

Seems to be related with the refactoring made on #56.

### PR DESCRIPTION
**Pull request by keul**
* Fixed an issue when the current user is an anonymous
* Check for HTTP_X_FORWARDED_FOR while getting user request info

fixes #57

### CODE REVIEW

**Comment by hvelarde** [comment]
thanks for fixing this! we were bitten by the same error but I didn't had time to fix it; quick question: do you know if `getMemberId()` and `getUserName()` return the same string for authenticated users?

previously I was using the user name included in the request, but I broke the code on a refactoring.

**Comment by keul** [comment]
@hvelarde sorry no bloody idea... I tried change code with minimal side effects changes. I don't have access to the test env today.

**Comment by hvelarde** [comment]
thanks! do you want a release today? I'm giving a training this week and I'm a little bit busy.

**Comment by hvelarde** [comment]
also, do you mind to add a test for this case so we avoid breaking it again in case of a later refactor?

**Comment by keul** [comment]
@hvelarde sure, I can work on this again adding tests next week. Let's keep PR open until I've done

**Comment by hvelarde** [comment]
thanks! if you want to add the translations, please do it on a different PR.

**Pull request merged**
